/*
 * CPOO Server API
 * This is a prototype of CPOO Project's front/back API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@mightycode.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorDTO;
import org.openapitools.client.model.FullUserDTO;
import org.openapitools.client.model.PublicMessageDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProfileApi
 */
@Disabled
public class ProfileApiTest {

    private final ProfileApi api = new ProfileApi();

    /**
     * Get the current information about the user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void userProfileGetTest() throws ApiException {
        FullUserDTO response = api.userProfileGet();
        // TODO: test validations
    }

    /**
     * Update information about the user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void userProfilePatchTest() throws ApiException {
        FullUserDTO fullUserDTO = new FullUserDTO();
        api.userProfilePatch(fullUserDTO);
        // TODO: test validations
    }

    /**
     * Remove the previous shared message to make it empty
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void userShareMessageDeleteTest() throws ApiException {
        api.userShareMessageDelete();
        // TODO: test validations
    }

    /**
     * Post a new public message (\&quot;status\&quot;) for all the current user friends and remove the previous one
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void userShareMessagePostTest() throws ApiException {
        PublicMessageDTO publicMessageDTO = null;
        api.userShareMessagePost(publicMessageDTO);
        // TODO: test validations
    }

}
