/*
 * CPOO Server API
 * This is a prototype of CPOO Project's front/back API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@mightycode.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ConversationDTO
 */
public class ConversationDTOTest {
    private final ConversationDTO model = new ConversationDTO();

    /**
     * Model tests for ConversationDTO
     */
    @Test
    public void testConversationDTO() {
        // TODO: test ConversationDTO
    }

    /**
     * Test the property 'userID'
     */
    @Test
    public void userIDTest() {
        // TODO: test userID
    }

    /**
     * Test the property 'peerAddress'
     */
    @Test
    public void peerAddressTest() {
        // TODO: test peerAddress
    }

    /**
     * Test the property 'lastMessageDate'
     */
    @Test
    public void lastMessageDateTest() {
        // TODO: test lastMessageDate
    }

}
