/*
 * CPOO Server API
 * This is a prototype of CPOO Project's front/back API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@mightycode.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MessageReducedDTO
 */
public class MessageReducedDTOTest {
    private final MessageReducedDTO model = new MessageReducedDTO();

    /**
     * Model tests for MessageReducedDTO
     */
    @Test
    public void testMessageReducedDTO() {
        // TODO: test MessageReducedDTO
    }

    /**
     * Test the property 'recipientID'
     */
    @Test
    public void recipientIDTest() {
        // TODO: test recipientID
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

}
