/*
 * CPOO Server API
 * This is a prototype of CPOO Project's front/back API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@mightycode.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MessageDTO
 */
public class MessageDTOTest {
    private final MessageDTO model = new MessageDTO();

    /**
     * Model tests for MessageDTO
     */
    @Test
    public void testMessageDTO() {
        // TODO: test MessageDTO
    }

    /**
     * Test the property 'msgID'
     */
    @Test
    public void msgIDTest() {
        // TODO: test msgID
    }

    /**
     * Test the property 'autorID'
     */
    @Test
    public void autorIDTest() {
        // TODO: test autorID
    }

    /**
     * Test the property 'recipientID'
     */
    @Test
    public void recipientIDTest() {
        // TODO: test recipientID
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'edited'
     */
    @Test
    public void editedTest() {
        // TODO: test edited
    }

}
