openapi: 3.0.3
info:
  contact:
    email: contact@mightycode.fr
    url: https://mightycode.fr/
  description: |
    This is a prototype of CPOO Project's front/back API.
  title: CPOO Server API
  version: 0.0.1
servers:
- url: http://localhost:8080/
security:
- CookieAuth: []
tags:
- description: User's authentication management
  name: authentication
- description: User's conversations management
  name: conversation
- description: User's messages management
  name: message
- description: User's profile information management
  name: profile
- description: User's contacts management
  name: contact
paths:
  /user/signup:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FullUserDTO'
        required: true
      responses:
        "200":
          description: Success
        "409":
          description: "Conflict, a user account with the same login already exists"
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      security: []
      tags:
      - authentication
      x-content-type: application/json
      x-accepts: application/json
  /user/signin:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
        required: true
      responses:
        "200":
          description: Success
          headers:
            Set-Cookie:
              explode: false
              schema:
                type: string
              style: simple
        "401":
          description: "Unauthorized, invalid login or password"
        "409":
          description: "Conflict, user already signed in (the session cookie is valid)"
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      security: []
      tags:
      - authentication
      x-content-type: application/json
      x-accepts: application/json
  /user/signout:
    post:
      responses:
        "200":
          description: Success
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      tags:
      - authentication
      x-accepts: application/json
  /user/delete:
    delete:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
        required: true
      responses:
        "200":
          description: Success
        "401":
          description: "Unauthorized, invalid password"
        "404":
          description: Current user not found
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      tags:
      - authentication
      x-content-type: application/json
      x-accepts: application/json
  /user/conversation/conversations:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ConversationDTO'
                type: array
          description: Provide the list of the conversations between the user and
            others
        "400":
          description: Bad request
        "404":
          description: Current user not found or conversations not found
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      summary: Retrieve all conversations (headers) between the current user and others
      tags:
      - conversation
      x-accepts: application/json
  /user/conversation/newConversation/{interlocutor}:
    post:
      parameters:
      - description: Username or peer address of the new interlocutor with whom to
          start a discussion
        explode: false
        in: path
        name: interlocutor
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationDTO'
          description: Create the new conversation and return the header
        "404":
          description: UserID not found in the users of the application
        "409":
          description: "Conflict, a conversation already exists with the given UserID"
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      summary: Create a new (empty) conversation with a given user
      tags:
      - conversation
      x-accepts: application/json
  /user/conversation/{login}:
    delete:
      parameters:
      - description: Username or peer address of the interlocutor from whom we want
          to delete the conversation
        explode: false
        in: path
        name: login
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: "Success, conversation deleted"
        "404":
          description: UserID not found in the current user's list of conversations
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      summary: Delete an existing conversation (the header and all contained messages)
        with a given user
      tags:
      - conversation
      x-accepts: application/json
    get:
      parameters:
      - description: Username or peer address of the interlocutor from whom we want
          to retrieve the conversation
        explode: false
        in: path
        name: login
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationDTO'
          description: Provide the header of the found conversation with the given
            user
        "410":
          description: "The conversation is no more available, has been deleted"
        "404":
          description: UserID not found in the current user's list of conversations
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      summary: Search an existing conversation (the header) with a given user
      tags:
      - conversation
      x-accepts: application/json
  /user/message/messages:
    get:
      description: Get all messages sent to or by the signed-in user. Messages are
        returned from the newest to the oldest.
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/MessageDTO'
                type: array
          description: Success
        "404":
          description: No conversation with this user
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      summary: Get all user's messages
      tags:
      - message
      x-accepts: application/json
  /user/message:
    post:
      description: Send a message on behalf of the signed-in user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewMessageDTO'
        required: true
      responses:
        "200":
          description: Success sending the message
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      summary: Send a message
      tags:
      - message
      x-content-type: application/json
      x-accepts: application/json
  /user/shareMessage:
    delete:
      responses:
        "200":
          description: "Success, delete the message"
        "410":
          description: "No shared message to delete, already empty"
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      summary: Remove the previous shared message to make it empty
      tags:
      - profile
      x-accepts: application/json
    post:
      requestBody:
        content:
          application/json:
            schema:
              description: Content of the message to share
              example: Hello everybody
              type: string
        required: true
      responses:
        "200":
          description: "Success, reset the previous post and share the message"
        "400":
          description: "Error, the message is too long"
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      summary: Post a new public message ("status") for all the current user friends
        and remove the previous one
      tags:
      - profile
      x-content-type: application/json
      x-accepts: application/json
  /user/profile:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullUserDTO'
          description: "Success, profile retrieved and returned"
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      summary: Get the current information about the logged user
      tags:
      - profile
      x-accepts: application/json
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FullUserDTO'
        required: true
      responses:
        "200":
          description: "Success, profile updated"
        "400":
          description: "Error, information types not valid"
        "401":
          description: "Error, unvalid authentification"
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      summary: Update information about the user
      tags:
      - profile
      x-content-type: application/json
      x-accepts: application/json
  /user/friend/{userID}:
    delete:
      parameters:
      - description: Username of the friend to remove
        explode: false
        in: path
        name: userID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: "Success, contact deleted"
        "404":
          description: UserID not found in the current user's list of friends
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      summary: Delete an existing contact (remove from the list of friends of the
        current user)
      tags:
      - contact
      x-accepts: application/json
    get:
      parameters:
      - description: Username of the friend to search
        explode: false
        in: path
        name: userID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactProfileDTO'
          description: Provide the header of the found contact profile of the given
            username
        "410":
          description: The user has been deleted
        "404":
          description: UserID not found in the current user's list of friends
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      summary: Search an existing contact in the list of the current user's friends
      tags:
      - contact
      x-accepts: application/json
    post:
      parameters:
      - description: Username of the user to add
        explode: false
        in: path
        name: userID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactProfileDTO'
          description: Add the user in the list of contacts (friends) and return the
            header contact profil of the new friend
        "410":
          description: The user has been deleted
        "404":
          description: UserID not found in the users of the application
        "409":
          description: UserID already existing in the list of friends
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      summary: Add a new contact to the current user's friends
      tags:
      - contact
      x-accepts: application/json
  /user/friends:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ContactProfileDTO'
                type: array
          description: Success
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      summary: Get the user's list of friends
      tags:
      - contact
      x-accepts: application/json
components:
  schemas:
    ErrorDTO:
      properties:
        timestamp:
          type: string
        status:
          type: integer
        error:
          type: string
        message:
          type: string
        path:
          type: string
      type: object
    UserDTO:
      example:
        remember: true
        password: abc2001/n
        login: anouk20
      properties:
        login:
          example: anouk20
          type: string
        password:
          example: abc2001/n
          type: string
        remember:
          description: To choose if the user wants to remember their information for
            next time
          example: true
          type: boolean
      required:
      - login
      - password
      - remember
      type: object
    FullUserDTO:
      allOf:
      - $ref: '#/components/schemas/UserDTO'
      - properties:
          icon:
            description: Number (ref) of the profile icon (image) of the user
            example: 6
            type: integer
          firstname:
            example: Anouk
            type: string
          lastname:
            example: Migliavacca
            type: string
          birthday:
            example: 06-20-2001
            type: string
          address:
            example: anouk.mi@pingpal
            type: string
        required:
        - address
        - birthday
        - firstname
        - icon
        - lastname
        type: object
    ConversationDTO:
      example:
        lastMessageDate: 10-10-2023 12:30:22
        userID: ambre_lv
        peerAddress: alv@domain
      properties:
        userID:
          description: Username of the interlocutor
          example: ambre_lv
          type: string
        peerAddress:
          example: alv@domain
          type: string
        lastMessageDate:
          description: Date of the last sent message to be able to sort conversations
            from the newest to the oldest
          example: 10-10-2023 12:30:22
          type: string
      required:
      - lastMessageDate
      - peerAddress
      type: object
    NewMessageDTO:
      description: New message information
      example:
        to: lvhoa@pingpal
        type: text/plain
        body: This is the message
      properties:
        to:
          example: lvhoa@pingpal
          type: string
        type:
          example: text/plain
          format: mime
          type: string
        body:
          example: This is the message
          type: string
      required:
      - body
      - to
      - type
      type: object
    MessageDTO:
      allOf:
      - $ref: '#/components/schemas/NewMessageDTO'
      - properties:
          id:
            example: 667bdc23-3de4-482f-a0f4-3391452a7742
            format: uuid
            type: string
          timestamp:
            example: 1720294759999
            format: int64
            type: integer
          from:
            example: anouk@pingpal
            type: string
        required:
        - from
        - id
        - timestamp
        type: object
      description: Message information
      example:
        to: lvhoa@pingpal
        type: text/plain
        body: This is the message
      properties:
        to:
          example: lvhoa@pingpal
          type: string
        type:
          example: text/plain
          format: mime
          type: string
        body:
          example: This is the message
          type: string
    ContactProfileDTO:
      example:
        birthday: 11-05-2003
        firstname: Ambre
        icon: 5
        userID: ambre_lv
        sharedMessage: Hi everybody!
        peerAddress: alv@domain
        lastname: Leveille
      properties:
        userID:
          description: Username (userID) of the contact
          example: ambre_lv
          type: string
        peerAddress:
          description: E-mail address of the contact
          example: alv@domain
          type: string
        icon:
          description: Number (ref) of the profile icon (image) of the user
          example: 5
          type: integer
        firstname:
          example: Ambre
          type: string
        lastname:
          example: Leveille
          type: string
        birthday:
          example: 11-05-2003
          type: string
        sharedMessage:
          description: Content of the public message (status) shared by the contact
            (can be empty)
          example: Hi everybody!
          type: string
      required:
      - birthday
      - firstname
      - icon
      - lastname
      - peerAddress
      - userID
      type: object
  securitySchemes:
    CookieAuth:
      description: Use a session cookie to authenticate (see /login).
      in: cookie
      name: JSESSIONID
      type: apiKey
x-samples-languages:
- curl
- javascript
- node
- java
- python
- php

