export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './contact.service';
import { ContactService } from './contact.service';
export * from './conversation.service';
import { ConversationService } from './conversation.service';
export * from './message.service';
import { MessageService } from './message.service';
export * from './profile.service';
import { ProfileService } from './profile.service';
export * from '../../services/user.service';
import { UserService } from '../../services/user.service';
export const APIS = [AuthenticationService, ContactService, ConversationService, MessageService, ProfileService, UserService];
