openapi: 3.0.3
info:
  contact:
    email: contact@mightycode.fr
    url: https://mightycode.fr/
  description: |
    This is a prototype of CPOO Project's front/back API.
  title: CPOO Server API
  version: 0.0.1
servers:
  - url: http://localhost:8080/
security:
  - CookieAuth: [ ]
tags:
  - name: authentication
    description: User authentication.
paths:
  /user/signup:
    post:
      security: [ ]
      tags:
        - authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FullUserDTO'
      responses:
        '200':
          description: Success
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /user/signin:
    post:
      security: [ ]
      tags:
        - authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '200':
          description: Success
          headers:
            Set-Cookie:
              schema:
                type: string
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /user/signout:
    post:
      tags:
        - authentication
      responses:
        '200':
          description: Success
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /user/delete:
    post:
      tags:
        - authentication
      responses:
        '200':
          description: Success
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /user/conversations:
    get:
      summary: Retrieve all conversations (headers) between the current user and others
      tags:
         - conversation
      responses:
        '200':
          description: Provide the list of the conversations between the user and others
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConversationDTO'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /user/{userID}/messages:
    get:
      summary: Retrieve all messages in a given conversation
      tags:
        - conversation
      parameters:
        - name: userID
          in: path
          description: Username of the interlocutor with whom the messages of the conversation are exchanged
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Provide the list of messages sent both by the user and his interlocutor for a given interlocutor
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MessageDTO'
        '404':
          description: UserID not found in the current user conversations
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /user/{userID}/message:
    post:
      summary: Send a new message to a given user
      tags:
        - conversation
      parameters:
        - name: userID
          in: path
          description: Username of the interlocutor to whom send a message
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageReducedDTO'
      responses:
        '200':
          description: Add the message to the list of messages with the given user and return the updated list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MessageDTO'
        '404':
          description: UserID not found
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /user/conversation/{user}:
    post:
      summary: Create a new (empty) conversation with a given user
      tags:
        - conversation
      parameters:
        - name: user
          in: path
          description: Username or peer address of the new interlocutor with whom to start a discussion
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Create the new conversation and return the header
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationDTO'
        '404':
          description: UserID not found in the users of the application
        '400':
          description: A conversation already exists with the given UserID
        default:
           description: Error
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/ErrorDTO'
    get:
      summary: Search an existing conversation (the header) with a given user
      tags:
        - conversation
      parameters:
        - name: user
          in: path
          description: Username or peer address of the interlocutor from whom we want to retrieve the conversation
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Provide the header of the found conversation with the given user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationDTO'
        '404':
          description: UserID not found in the current user's list of conversations
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
    delete:
      summary: Delete an existing conversation (the header and all contained messages) with a given user
      tags:
        - conversation
      parameters:
        - name: user
          in: path
          description: Username or peer address of the interlocutor from whom we want to delete the conversation
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success, conversation deleted
        '404':
          description: UserID not found in the current user's list of conversations
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /user/conversation/{msgID}:
    patch:
      summary: Modify a certain message already sent
      tags:
        - conversation
      parameters:
        - name: msgID
          in: path
          description: ID of the message to modify in the list of messages
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: New content of the message
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: Success, return modified message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageDTO'
        '404':
          description: msgID not found in the list of messages
        default:
            description: Error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorDTO'
    delete:
      summary: Delete a message already sent
      tags:
        - conversation
      parameters:
        - name: msgID
          in: path
          description: ID of the message to delete in the list of messages
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success, message deleted
        '404':
          description: UserID not found in the list of messages
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /user/shareMessage:
    post:
      summary: Post a new public message ("status") for all the current user friends and remove the previous one
      tags:
        - profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublicMessageDTO'
      responses:
        '200':
          description: Success, reset the previous post and share the message
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
    delete:
      summary: Remove the previous shared message to make it empty
      tags:
        - profile
      responses:
        '200':
          description: Success, delete the message (also if it was already empty)
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /user/profile:
    get:
      summary: Get the current information about the user
      tags:
        - profile
      responses:
        '200':
          description: Success, profile retrieved and returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullUserDTO'
        '400':
          description: Error, could not retrieve the current information about the user
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
    patch:
      summary: Update information about the user
      tags:
        - profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FullUserDTO'
      responses:
        '200':
          description: Success, updated profile returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullUserDTO'
        '400':
          description: Error, could not retrieve the information updated
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /user/friend/{userID}:
    post:
      summary: Add a new contact to the current user's friends
      tags:
        - contact
      parameters:
        - name: userID
          in: path
          description: Username of the user to add
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Add the user in the list of contacts (friends) and return the header contact profil of the new friend
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactProfileDTO'
        '404':
          description: UserID not found in the users of the application
        '400':
          description: UserID already existing in the list of friends
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
    get:
      summary: Search an existing contact in the list of the current user's friends
      tags:
        - contact
      parameters:
        - name: userID
          in: path
          description: Username of the friend to search
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Provide the header of the found contact profil of the given username
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactProfileDTO'
        '404':
          description: UserID not found in the current user's list of friends
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
    delete:
      summary: Delete an existing contact (remove from the list of friends of the current user)
      tags:
        - contact
      parameters:
        - name: userID
          in: path
          description: Username of the friend to remove
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success, contact deleted
        '404':
          description: UserID not found in the current user's list of friends
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /user/friends:
    get:
      summary: Get the user's list of friends
      tags:
        - contact
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ContactProfileDTO'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'

components:
  schemas:
    ErrorDTO:
      type: object
      properties:
        timestamp:
          type: string
        status:
          type: integer
        error:
          type: string
        message:
          type: string
        path:
          type: string
    UserDTO:
      type: object
      properties:
        login:
          type: string
          example: anouk20
        password:
          type: string
          example: abc2001/n
        remember:
          type: boolean
          description: To choose if the user wants to remember their information for next time
          example: true
      required:
        - login
        - password
        - remember
    FullUserDTO:
      allOf:
        - $ref: '#/components/schemas/UserDTO'
        - type: object
          properties:
            icon:
              type: integer
              description: Number (ref) of the profile icon (image) of the user
              example: 6
            firstname:
              type: string
              example: Anouk
            lastname:
              type: string
              example: Migliavacca
            birthday:
              type: string
              format: date-time
              example: 06/20/2001
            address:
              type: string
              example: anouk.mi@domain
          required:
            - icon
            - firstname
            - lastname
            - birthday
            - address
    ConversationDTO:
      type: object
      properties:
        userID:
          type: string
          description: Username of the interlocutor
          example: ambre_lv
        peerAddress:
          type: string
          example: alv@domain
        lastMessageDate:
          type: string
          format: date-time
          description : Date of the last sent message to be able to sort conversations from the newest to the oldest
          example: 10/10/2023 12:30:22
      required:
        - peerAddress
        - lastMessageDate
    MessageReducedDTO:
      type: object
      properties:
        recipientID:
          type: string
          description: Username (userID) of the interlocutor or the peerAddress
          example: anouk20 OR anouKmi@domain
        content:
          type: string
          description: Text contained in the message
          example: Hello friend
      required:
        - recipientID
        - content
    MessageDTO:
      allOf :
        - $ref: '#/components/schemas/MessageReducedDTO'
        - type: object
          properties:
            msgID:
              type: integer
              format: int64
              description: ID of the message in the list of messages
              example: 1029374
            autorID:
              type: string
              description: Username (userID) of the writer if it's a registered user of the app
              example: ambre_lv
            autorAddress :
              type: string
              description: PeerAddress of the writer
              example: alv@domain
            date:
              type: string
              format: date-time
              description: Date of the message to be able to sort messages from the newest to the oldest
              example: 10/10/2023 12:30:22
            edited:
              type: boolean
              description: True if message has been edited, false otherwise
              example: false
          required :
            - msgID
            - autorAddress
            - date
            - edited
    PublicMessageDTO:
      type: object
      properties:
        userID:
          type: string
          description: Username (userID) of the writer
          example: anouk20
        content:
          type: string
          description: Text contained in the message
          example: Hello everybody
      required:
        - userID
        - content
    ContactProfileDTO:
      type: object
      properties:
        userID:
          type: string
          description: Username (userID) of the contact
          example: ambre_lv
        peerAddress:
          type: string
          description: E-mail address of the contact
          example: alv@domain
        icon:
          type: integer
          description: Number (ref) of the profile icon (image) of the user
          example: 5
        firstname:
          type: string
          example: Ambre
        lastname:
          type: string
          example: Leveille
        birthday:
          type: string
          format: date-time
          example: 01/05/2003
        sharedMessage :
          type: string
          description: Content of the public message (status) shared by the contact (can be empty)
          example: Hi everybody!
      required:
        - userID
        - peerAddress
        - icon
        - firstname
        - lastname
        - birthday

  securitySchemes:
    CookieAuth:
      type: apiKey
      in: cookie
      name: JSESSIONID
      description: Use a session cookie to authenticate (see /login).
x-samples-languages:
  - curl
  - javascript
  - node
  - java
  - python
  - php
